name: Test PRs

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache bundled gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        # We'd normally use Gemfile.lock, but nonexistent here.
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Build the site
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install
        bundle exec jekyll build

    - name: Test the HTML
      run: |
        bundle exec htmlproofer ~/workspace \
          --allow-hash-href \
          --check-html \
          --empty-alt-ignore \
          --url-ignore "/github.com\/hyphacoop\/organizing-private/,/github.com\/issues/"
